language: node_js
node_js:
  - '0.12'
  - '0.10'

addons:
  apt:
    packages:
      - lintian

before_install:
  - npm install -g grunt-cli

after_success:
  - lintian test/fixtures/out/foo_i386.deb
  - lintian test/fixtures/out/bar_amd64.deb
