---
dist: trusty
sudo: required

language: node_js

services:
  - docker

before_install:
  - docker pull endlessm/electron-flatpak

install:
  - docker run --privileged -v $PWD:/build:rw endlessm/electron-flatpak /bin/bash -c "cd /build && npm install"

script:
  - docker run --privileged -v $PWD:/build:rw endlessm/electron-flatpak /bin/bash -c "cd /build && npm test"
